apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arffornia-website.fullname" . }}
  labels:
    {{- include "arffornia-website.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arffornia-website.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "arffornia-website.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arffornia-website.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.env }}
      env:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.envFrom }}
      envFrom:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.initContainers.enabled }}
      initContainers:
        - name: {{ .Chart.Name }}-database-migrations
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}

          {{- with .Values.initContainers.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.initContainers.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}-backend
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.images.backend.port }}
              protocol: TCP

          {{- if .Values.liveness.enabled }}
          livenessProbe:
            {{- toYaml .Values.liveness.spec | nindent 12 }}
          {{- end }}
          {{- if .Values.readiness.enabled }}
          readinessProbe:
            {{- toYaml .Values.readiness.spec | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: {{ .Chart.Name }}-frontend
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          env:
            - name: TARGET_HOST
              value: {{ .Values.images.backend.host | default "127.0.0.1" | quote }}
            - name: TARGET_PORT
              value: {{ .Values.images.backend.port | default 9000 | quote }}
            - name: LISTEN_PORT
              value: {{ .Values.service.port | quote }}

          {{- if .Values.liveness.enabled }}
          livenessProbe:
            {{- toYaml .Values.liveness.spec | nindent 12 }}
          {{- end }}
          {{- if .Values.readiness.enabled }}
          readinessProbe:
            {{- toYaml .Values.readiness.spec | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
