name: Deploy Arffornia

on:
    push:
        branches:
            - main

jobs:
    create-deployment-artifacts:
        name: Create deployment artifacts
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4

            - name: Compile CSS and Javascript
              run: 
                npm install
                npm run prod

            - name: Configure PHP 8.2
              uses: shivammathur/setup-php@master
              with:
                php-version: 8.2
                extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
